name: Artifact Name Validation

on: [push]

jobs:
  validate-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Validate Artifact Name
      run: |
        artifact_name="invalid_artifactname.zip"
        if [[ $artifact_name =~ ^[a-zA-Z0-9_-]+\.zip$ ]]; then
          echo "Artifact name is valid"
        else
          echo "Invalid artifact name"
          exit 1
        fi

    - name: Upload Artifact
      if: success()
      run: |
        jf rt upload invalid_artifactname.zip my-repo-generic-local/
